# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/prezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/prezto/init.zsh"
fi

# Add User/bin if it is available
# Linux
if [[ -d "${HOME}/bin" ]]; then
  export PATH="$HOME/bin:$PATH"
fi

# macOS
if [[ -d "${HOME}/Applications/Bin" ]]; then
  export PATH="$HOME/Applications/Bin:$PATH"
fi

# Customize to your needs...
if [[ -s "${ZDOTDIR:-$HOME}/zshrc_local" ]]; then
  source "${ZDOTDIR:-$HOME}/zshrc_local"
fi

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh
